project:
  type: website

website:
  title: "Team05"
  navbar:
    left:
      - href: index.qmd
        text: Title
      - href: about.qmd
        text: Title2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

