project:
  type: website

website:
  title: "Team 05 Örebro University"
  navbar:
    left:
      - href: index.qmd
        text: "Project Description"
      - href: about.qmd
        text: "Portugal"
      - href: greece.qmd
        text: "Greece"
      - href: spain.qmd
        text: "Spain"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

