project:
  type: website

website:
  title: "Team05"
  navbar:
    left:
      - href: index.qmd
        text: "Project Description"
      - href: about.qmd
        text: "Dashboard"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

